// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaEhfHmrV8fXfClz3GP0jKqvOygkRUusk',
    appId: '1:530960691637:android:f9a224567e66568a24a9fc',
    messagingSenderId: '530960691637',
    projectId: 'plato-calendar',
    storageBucket: 'plato-calendar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-lh4qSfSGWFmbC6AcEHGnCYOiey0lPO0',
    appId: '1:265471427528:ios:901cc1dff6252bc764b6fd',
    messagingSenderId: '265471427528',
    projectId: 'plato-calendar-2ae66',
    storageBucket: 'plato-calendar-2ae66.firebasestorage.app',
    androidClientId:
        '530960691637-18bfv265ou24630kftgb44dtfgsii0jl.apps.googleusercontent.com',
    iosClientId:
        '265471427528-ovjr7gsvb1liv1r4esmh1b3ucs5k5u6r.apps.googleusercontent.com',
    iosBundleId: 'com.junseo.platoCalendar',
  );
}
